### PR TITLE
Localize Done button on navigation bar

### PR DESCRIPTION
**Pull request by vvit**
I think changing Done button title can also be useful. What do you think?
Thanks.

### CODE REVIEW

**Comment by yackle** [comment]
That would be nice! Please wait to become ready.

**Comment by yackle** [comment]
I had just an idea. I think the following modification is better for compatibility of Localizable.strings.

```
    NSString *doneBtnTitle = [CLImageEditorTheme localizedString:@"CLImageEditor_DoneBtnTitle" withDefault:@""];
    
    if(doneBtnTitle.length>0){
        self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:doneBtnTitle style:UIBarButtonItemStyleDone target:self action:@selector(pushedFinishBtn:)];
    }
    else{
        self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(pushedFinishBtn:)];
    }
```

How about you?

**Comment by vvit** [comment]
Sounds good to me, thx!

**Comment by yackle** [comment]
merged, and modified 5d80b853f3206560c70cb014a625380be09298bd

Thanks!

**Comment by vvit** [comment]
@yackle thx, but you forgot to remove ```"CLImageEditor_DoneBtnTitle" = "Done";``` from ```CLImageEditor.bundle/Resources/en.lproj/Localizable.strings``` to make it work as expected :)

**Comment by yackle** [comment]
it is probably fixed, please check it.

**Pull request merged**
